public struct AttributeName {
  public let name: String
}

extension AttributeName {
  // Etc.
  public static let accept = AttributeName(name: "accept")
  public static let autocapitalize = AttributeName(name: "autocapitalize")
  public static let autocomplete = AttributeName(name: "autocomplete")
  public static let autocorrect = AttributeName(name: "autocorrect")
  public static let autofocus = AttributeName(name: "autofocus")
  public static let autosave = AttributeName(name: "autosave")
  public static let acceptCharset = AttributeName(name: "accept-charset")
  public static let action = AttributeName(name: "action")
  public static let alt = AttributeName(name: "alt")
  public static let async = AttributeName(name: "async")
  public static let charset = AttributeName(name: "charset")
  public static let checked = AttributeName(name: "checked")
  public static let content = AttributeName(name: "content")
  public static let cite = AttributeName(name: "cite")
  public static let crossorigin = AttributeName(name: "crossorigin")
  public static let cols = AttributeName(name: "cols")
  public static let colspan = AttributeName(name: "colspan")
  public static let contentType = AttributeName(name: "type")
  public static let disabled = AttributeName(name: "disabled")
  public static let deferred = AttributeName(name: "defer")
  public static let enctype = AttributeName(name: "enctype")
  public static let forInput = AttributeName(name: "for")
  public static let form = AttributeName(name: "form")
  public static let formaction = AttributeName(name: "formaction")
  public static let formmethod = AttributeName(name: "formmethod")
  public static let formtarget = AttributeName(name: "formtarget")
  public static let formvalidate = AttributeName(name: "formvalidate")
  public static let headers = AttributeName(name: "headers")
  public static let height = AttributeName(name: "height")
  public static let httpEquiv = AttributeName(name: "http-equiv")
  public static let href = AttributeName(name: "href")
  public static let hreflang = AttributeName(name: "hreflang")
  public static let inputmode = AttributeName(name: "inputmode")
  public static let inputType = AttributeName(name: "type")
  public static let label = AttributeName(name: "label")
  public static let max = AttributeName(name: "max")
  public static let maxlength = AttributeName(name: "maxlenth")
  public static let min = AttributeName(name: "min")
  public static let minlength = AttributeName(name: "minlength")
  public static let method = AttributeName(name: "method")
  public static let multiple = AttributeName(name: "multiple")
  public static let name = AttributeName(name: "name")
  public static let novalidate = AttributeName(name: "novalidate")
  public static let pattern = AttributeName(name: "pattern")
  public static let placeholder = AttributeName(name: "placeholder")
  public static let readonly = AttributeName(name: "readonly")
  public static let required = AttributeName(name: "required")
  public static let rel = AttributeName(name: "rel")
  public static let results = AttributeName(name: "results")
  public static let reversed = AttributeName(name: "reversed")
  public static let rows = AttributeName(name: "rows")
  public static let rowspan = AttributeName(name: "rowspan")
  public static let scope = AttributeName(name: "scope")
  public static let selected = AttributeName(name: "selected")
  public static let selectionDirection = AttributeName(name: "selectionDirection")
  public static let scriptType = AttributeName(name: "type")
  public static let selectionEnd = AttributeName(name: "selectionEnd")
  public static let selectionStart = AttributeName(name: "selectionStart")
  public static let sizes = AttributeName(name: "sizes")
  public static let size = AttributeName(name: "size")
  public static let spellcheck = AttributeName(name: "spellcheck")
  public static let src = AttributeName(name: "src")
  public static let srcset = AttributeName(name: "srcset")
  public static let start = AttributeName(name: "start")
  public static let step = AttributeName(name: "step")
  public static let tabindex = AttributeName(name: "tabindex")
  public static let target = AttributeName(name: "target")
  public static let text = AttributeName(name: "text")
  public static let value = AttributeName(name: "value")
  public static let width = AttributeName(name: "width")
  public static let wrap = AttributeName(name: "wrap")
  public static let xmlns = AttributeName(name: "xmlns")

  // Global attributes
  public static let accesskey = AttributeName(name: "accesskey")
  public static let classname = AttributeName(name: "class")
  public static let contenteditable = AttributeName(name: "contenteditable")
  public static let contextmenu = AttributeName(name: "contextmenu")
  public static let dir = AttributeName(name: "dir")
  public static let draggable = AttributeName(name: "draggable")
  public static let data = AttributeName(name: "data")
  public static let dropzone = AttributeName(name: "dropzone")
  public static let hidden = AttributeName(name: "hidden")
  public static let id = AttributeName(name: "id")
  public static let title = AttributeName(name: "title")
}
